export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const SAVE_TASKS_SUCCESS = "SAVE_TASKS_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";

export const SET_ACTIVE_BOOKING = "SET_ACTIVE_BOOKING";
export const FETCH_BOOKING_ERROR = "FETCH_BOOKING_ERROR";
export const SAVE_BOOKING = "SAVE_BOOKING";
export const DELETE_SAVED_BOOKING = "DELETE_SAVED_BOOKING";
export const CLEAR_SAVED_BOOKINGS = "CLEAR_SAVED_BOOKINGS";

export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DEKETE_FLASH_MESSAGE";
