export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const SAVE_TASKS_SUCCESS = "SAVE_TASKS_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const ADD_TASK = "ADD_TASK";

export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
